### PR TITLE
exclude `update` for Clojure 1.7

### PR DESCRIPTION
**Pull request by xpe**
In response to https://github.com/r0man/sqlingvo/issues/26

### CODE REVIEW

**Comment by xpe** [comment]
This may not be ready to merge, as is. What's a good way to test against both 1.7-alpha5 and 1.6?

**Comment by r0man** [comment]
hi @xpe,

I think we need a Leiningen profile. Take a look at this for example:

https://github.com/weavejester/compojure/blob/master/project.clj#L21
https://github.com/weavejester/compojure/blob/master/.travis.yml#L3

Roman

**Comment by xpe** [comment]
@r0man done with https://github.com/orphid/sqlingvo/commit/c814438e2b0923d6f00bfb5294fd453d6dadcd61

**Comment by r0man** [comment]
Hi @xpe,

could squash the commits into one and remove your namespace from the defproject, so I can merge this please.

Thanks Roman.

**Comment by r0man** [comment]
Released as `0.7.10`.

**Pull request closed without merging**
