### PR TITLE
first pass at implementing foreign key constraint on column definition

### PR DESCRIPTION
**Pull request by daviddpark**
still need a foreign-key function to be feature complete

@r0man, would you consider this PR for issue #15?

I don't have time right now to implement the foreign-key that would enable multi-column support, but hope to get to it shortly.

### CODE REVIEW

**Comment by daviddpark** [comment]
As the core.name function treats :spots/id as a namespace qualified variable, and parentheses are not legal in a keyword, I switched the references argument to a string. I am sure that that inconsistency will not sit well with you, do you have a better idea?

Thanks for considering my pull request.

**Comment by r0man** [comment]
@daviddpark Sorry for the late response. I'm traveling at the moment. You are right, that I don't like the string approach :) Why not write a function that converts `:spots/id` into the correct string and use that one? Also, could you take a look at multi column support? It shouldn't be too hard. If `:references` is an array join those columns together?

**Comment by daviddpark** [comment]
No worries on timeliness, hope you are enjoying your traveling. The problem with :spots/id is that the keyword is qualified into the spots namespace. Perhaps if we used a separator other than "/"? :spots.id perhaps.

I think multi column support can be achieved by using references on each column definition individually, or perhaps with a "foreign-key" function similar to the "primary-key" function, but do not see how passing an array to :references during the column declaration makes much sense. Unless I am missing something, a column in a child table can only reference a single column in a parent table, so in the column definition it makes sense to only have a single value for :references.

A single child table can have several keys that act as a complex foreign key to a parent table, but I think this must be declared during create-table and not on the individual column definitions.

**Comment by r0man** [comment]
Fixed in master

**Pull request closed without merging**
